---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову
  - Пользователь должен иметь возможность искать товары по категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать список товаров с использованием постраничного вывода
  - Пользователь должен иметь возможность просматривать подробную информацию о товаре
  - В каталоге товаров и на странице товара должны отображаться - название товара, рейтинг, цена без скидки, цена со скидкой
  - Пользователь должен иметь возможность добавлять товары в корзину
  - Пользователь должен иметь возможность просматривать содержимое корзины
  - Пользователь должен иметь возможность удалять товары из корзины
  - Пользователь должен иметь возможность продолжить выбор товаров после добавления товара в корзину
  - Пользователь должен иметь возможность продолжить выбор товаров из каталога со страницы корзины
  - Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты
  - Пользователь должен иметь возможность переключить язык интерфейса
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь адаптивную верстку и корректно отображаться на мобильных устройствах
  - Приложение должно быть реализовано как SPA (Single Page Application) без полной перезагрузки страницы
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь возможность локализацию (русский и английский языки)
  - Корзина должна храниться в сессии браузера
  - Сайт должен быть доступен для пользователей без использования VPN (прямой доступ из сети Интернет)
implicit:
  - Изображение товара должно корректно отображаться
  - Если товары не найдены, пользователю должно отображаться соответствующее сообщение
  - Общая стоимость корзины должна пересчитываться после добавления или удаления товара
